require("bar")
require("default")

require("items.spaces")
require("items.indicator")
require("items.right_spacer")
require("items.battery")
require("items.wifi")
require("items.volume")
require("items.date")
require("items.notch")
require("items.clock")
require("items.github_reviews")
require("items.brackets")
