hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/random-wallpaper.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("hypridle")
end)
