################
### MONITORS ###
################

# Workstation: Current config (unchanged)
monitor=, highres@highrr, auto, 1
monitor=, preferred, auto-center-down, 1

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = HYPRCURSOR_THEME, Nordzy-cursors
env = HYPRCURSOR_SIZE,36
env = XCURSOR_THEME, Nordzy-cursors
env = XCURSOR_SIZE,36
