config-version = 2

after-startup-command = [
  'exec-and-forget /bin/bash -c "/run/current-system/sw/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(/run/current-system/sw/bin/aerospace list-workspaces --focused)"'
]

exec-on-workspace-change = ['/bin/bash', '-c',
    '/run/current-system/sw/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = false

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 5

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = []

automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       3
    outer.bottom =     3
    outer.top =        [{ monitor.main = 3 }, 43]
    outer.right =      3

[mode.main.binding]
    cmd-enter = 'exec-and-forget open -na "WezTerm.app"'
    cmd-n = 'exec-and-forget open -na "Brave Browser.app"'
    cmd-q = 'close'

    cmd-h = 'focus left --boundaries all-monitors-outer-frame'
    cmd-j = 'focus down --boundaries all-monitors-outer-frame'
    cmd-k = 'focus up --boundaries all-monitors-outer-frame'
    cmd-l = 'focus right --boundaries all-monitors-outer-frame'
    cmd-ctrl-h = 'join-with left'
    cmd-ctrl-j = 'join-with down'
    cmd-ctrl-k = 'join-with up'
    cmd-ctrl-l = 'join-with right'

    cmd-shift-r = 'reload-config'
    ctrl-cmd-v = 'layout floating tiling'

    cmd-shift-h = 'move left --boundaries all-monitors-outer-frame'
    cmd-shift-j = 'move down --boundaries all-monitors-outer-frame'
    cmd-shift-k = 'move up --boundaries all-monitors-outer-frame'
    cmd-shift-l = 'move right --boundaries all-monitors-outer-frame'

    cmd-shift-u = 'resize width -50'
    cmd-shift-p = 'resize width +50'
    cmd-shift-i = 'resize height -50'
    cmd-shift-o = 'resize height +50'

    ctrl-1 = 'workspace 1'
    ctrl-2 = 'workspace 2'
    ctrl-3 = 'workspace 3'
    ctrl-4 = 'workspace 4'
    ctrl-5 = 'workspace 5'
    ctrl-6 = 'workspace 6'
    ctrl-7 = 'workspace 7'
    ctrl-8 = 'workspace 8'
    ctrl-9 = 'workspace 9'
    ctrl-0 = 'workspace 0'

    ctrl-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    ctrl-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    ctrl-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    ctrl-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    ctrl-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
    ctrl-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
    ctrl-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
    ctrl-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
    ctrl-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
    ctrl-shift-0 = 'move-node-to-workspace 0 --focus-follows-window'

    cmd-tab = 'workspace-back-and-forth'
    cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'main'
    6 = 'secondary'
    7 = 'secondary'
    8 = 'secondary'
    9 = 'secondary'
    0 = 'secondary'

